import os

# Base directory paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PARQUET_PATH_REALTIME = os.path.join(BASE_DIR, "metrics_realtime.parquet")
PARQUET_PATH_AGGREGATED = os.path.join(BASE_DIR, "metrics_aggregated.parquet")
BACKTEST_REPORT_PATH = os.path.join(BASE_DIR, "full_backtest_report.png")

# Fees / HFT constants
FEES_TAKER_A = 0.0004
FEES_MAKER_A = 0.0001
FEES_TAKER_B = 0.0002
FEES_MAKER_B = 0.00009
FEES_TAKER_C = 0.0003
FEES_MAKER_C = 0.00009

# MarketMaker constants
FLUSH_INTERVAL = 1_000
MARKET_MAKER_WEIGHT_B = 0.75
MARKET_MAKER_WEIGHT_C = 0.25
MARKET_MAKER_LATENCY_B = 0.200
MARKET_MAKER_LATENCY_C = 0.170
MARKET_MAKER_DELTA_TAU = 0.150
MARKET_MAKER_HEDGE_THRESHOLD = 0.90
MARKET_MAKER_EPSILON = 0.00005
MARKET_MAKER_AGGREGATION_STEPS = 100
INVENTORY_REGIME_NORMAL_THRESHOLD = 0.75
INVENTORY_REGIME_ALERT_THRESHOLD = 0.90

# Phase 3 — fallback MM on A (behind HFT, latency buffer, stress / wide-spread reaction)
MARKET_MAKER_PHASE3_HEDGE_LEG_TRIGGER = 0.88
MM_PHASE3_LATENCY_SAFETY_BUFFER_PIPS = 1.5
MM_PHASE3_DEEPEN_BASE_TICKS = 4.0
MM_PHASE3_TICK = 0.0001
MM_PHASE3_HFT_QTY_REFERENCE = 500_000.0
MM_PHASE3_MAX_EXTRA_TICKS_FROM_HFT = 6.0
MM_PHASE3_FALLBACK_SPREAD_MULTIPLIER = 2.2
MM_PHASE3_HFT_MIN_TOTAL_QTY = 25_000.0
MM_PHASE3_FALLBACK_DEPTH_PULL_TICKS = 3.0
MM_PHASE3_FALLBACK_BUFFER_SCALE = 0.45
MM_PHASE3_EMA_SPREAD_ALPHA = 0.02
MM_PHASE3_INVENTORY_RAMP_START_LEG = 0.78
MM_PHASE3_INVENTORY_RAMP_END_LEG = 0.90
MM_PHASE3_INVENTORY_SKEW_STRENGTH = 2.0
MM_PHASE3_SIDE_DEPTH_INV_SCALE = 0.55

# Strategy constants
DEFAULT_MAX_LEVELS = 10
DEFAULT_TICK_SIZE = 0.0001
DEFAULT_GEO_INCREMENT = 1.4
DEFAULT_GEO_QTY_ALPHA = 0.7
MIN_REMAINING_TIME = 0.001
PIPS_TO_PRICE_SCALE = 10_000.0
DEFAULT_FEES_PIPS = 2.0
DEFAULT_INITIAL_CAPITAL = 1_000_000.0

# Backtest / simulator constants
BACKTEST_DEFAULT_DAYS = 1
BACKTEST_DEFAULT_STEPS = 5_000
BACKTEST_DEFAULT_DT = 0.01
BACKTEST_MID_START = 1.15
BACKTEST_MM_USD_QUANTITY = 700_000.0
BACKTEST_MM_EUR_QUANTITY = 300_000.0 / BACKTEST_MID_START
BACKTEST_MM_GAMMA = 0.05
BACKTEST_MM_SIGMA = 0.0005
BACKTEST_MM_KAPPA = 200
ORGANIC_BOOK_DEPTH_LEVELS = 10
ORGANIC_BOOK_LEVEL_QTY = 500_000
SIMULATOR_BUFFER_B_SIZE = 21
SIMULATOR_BUFFER_C_SIZE = 18
SIMULATOR_HFT_LOOKBACK_STEPS = 5
SIMULATOR_HEDGE_LOOKBACK_B = 20
SIMULATOR_HEDGE_LOOKBACK_C = 17
SIMULATOR_PROGRESS_LOG_INTERVAL = 500
SIMULATOR_TOP_TRADES_COUNT = 10
SIMULATOR_STEP_DT = 0.01
SIMULATOR_RANDOM_BUY_PROB = 0.5
SIMULATOR_ORGANIC_LAMBDA_SCALE = 0.01
SIMULATOR_LOG_PROGRESS_SCALE = 100
# Phase: 1 = organic + MM only (no HFT). 2 = + HFT cross-venue snipe. 3 = + HFT make_market_on_A (uses HFT_PROB_*).
SIMULATOR_DEFAULT_PHASE = 1
SIMULATOR_PHASE1_ORGANIC_LAMBDA_MULTIPLIER = 3.0

# Backtest plotting constants
PLOT_FIGSIZE = (18, 14)
PLOT_GRIDSPEC_ROWS = 4
PLOT_GRIDSPEC_COLS = 2
PLOT_DPI = 300
INVENTORY_ALERT_LINE_PCT = 70
INVENTORY_YMAX_PCT = 100
PIPS_MULTIPLIER = 10_000
HFT_MARKER_SIZE_DIVISOR = 1_000
TABLE_FONT_SIZE = 10
TABLE_SCALE_X = 1
TABLE_SCALE_Y = 1.5
FILL_RATE_YMAX_MULTIPLIER = 1.5
FALLBACK_FILL_RATE_YMAX = 1

# OrderBook evolution/test constants
ORDERBOOK_DEFAULT_LEVELS = 20
ORDERBOOK_DEFAULT_TICK_SIZE = 0.0001
ORDERBOOK_DEFAULT_MO_BUY_PROB = 0.5
ORDERBOOK_ADVANCED_TEST_LEVEL_COUNT = 50
ORDERBOOK_ADVANCED_TEST_STEPS = 100
ORDERBOOK_ADVANCED_TEST_SNAPSHOT_INTERVAL = 25
ORDERBOOK_ADVANCED_TEST_RANDOM_SEED = 42
ORDERBOOK_ADVANCED_TEST_DT = 0.01
ORDERBOOK_ADVANCED_TEST_DRIFT_SCALE = 0.00001
ORDERBOOK_ADVANCED_TEST_BOOK_DEPTH = 10

# Smoke test constants
SMOKE_TEST_N_LEVELS = 5
SMOKE_TEST_STEPS = 100
SMOKE_TEST_SEED = 42
SMOKE_TEST_MM_SIGMA = 8.33e-6
SMOKE_TEST_MM_KAPPA = 5000
SMOKE_TEST_MM_HORIZON = 24 * 3600
SMOKE_TEST_MM_Q_MAX = 1_000_000.0

# OrderBook constants
LAMBDA_A0_B = 5.0
ALPHA_B = 0.05
THETA_B = 0.1
LAMBDA_MO_B = 2.0
V_UNIT_B = 100_000

LAMBDA_A0_C = 5.0
ALPHA_C = 0.05
THETA_C = 0.1
LAMBDA_MO_C = 2.0
V_UNIT_C = 100_000

# Exchange A defaults
LAMBDA_A0_A = 50.0
ALPHA_A = 0.05
THETA_A = 0.1
LAMBDA_MO_A = .05
V_UNIT_A = 50_000

# Price simulator defaults
PRICE_SIM_DEFAULT_S0 = 1.0850
PRICE_SIM_DEFAULT_DT_SECONDS = 0.01
PRICE_SIM_DEFAULT_BAR_SIGMA_PIPS = 5.0
PRICE_SIM_DEFAULT_LAMBDA_JUMP_PER_DAY = 4.0
PRICE_SIM_DEFAULT_SIGMA_JUMP_PIPS = 7.5
PRICE_SIM_DEFAULT_RHO_EPS = 0.9
PRICE_SIM_DEFAULT_SIGMA_EPS_PIPS = 5.0
SECONDS_PER_HOUR = 3600.0
HOURS_PER_DAY = 24.0
SECONDS_PER_DAY = 86_400
PRICE_SIM_DEFAULT_DAY_STEPS = 8_640_000
TOKYO_ACTIVITY = 0.6
LONDON_OPEN_ACTIVITY = 1.4
LONDON_MID_ACTIVITY = 1.0
OVERLAP_ACTIVITY = 1.5
POST_LONDON_ACTIVITY = 0.8
OVERNIGHT_ACTIVITY = 0.5

# Poisson model defaults
ARRIVAL_INTENSITY_DEFAULT_SPREAD = 0.01
ARRIVAL_INTENSITY_DEFAULT_ALPHA = 0.1
ARRIVAL_INTENSITY_DEFAULT_LAMBDA_0 = 0.5

# Constraint for Optim
MAX_SPREAD_PIPS   = 5.0 # in pips
MIN_QTY_QUOTED    = 100_000
HEDGE_THRESHOLD   = 0.9

# HFT constants
HFT_PROB_OFF = 0.0  # probability of turning off HFT
HFT_PROB_ONE_SIDED = 0.0  # probability of quoting only one side of the book